Default wrist_tform_tool to identity
bdaiinstitute/spot_wrapper pull request #149
Opened 2024-11-07 21:04 UTC by llee-bdai

Turns out `ArmCartesianCommand` defaults `wrist_tform_tool` to be some approximately 20cm offset https://dev.bostondynamics.com/protos/bosdyn/api/proto_reference#armcartesiancommand-request

This PR sets the transform to be identity so that when you send a hand pose, it's commanding the wrist to the pose, and not wrist plus some unknown defaulted offset.

2024-11-07 21:07 UTC, amessing-bdai commented on spot_wrapper/spot_arm.py
> +                wrist_tform_tool=geometry_pb2.SE3Pose(
@llee-bdai Is this the function that you recently fixed? I am trying to figure out how much of a breaking change this is.

2024-11-07 21:37 UTC, scastro-bdai reviewed
Given that this function is called `hand_pose` but really sets the pose of the arm, and also is called in the `arm_pose_cmd_callback` of the `SpotROS` node...

how would you feel about

1. Renaming this to `set_arm_pose()`
2. Actually making this transform an argument of the function instead of hard-coding, but still defaulting it to identity?
3. Making the above default arg an `SE3` and converting it to the protobuf inside this function body?

2024-11-07 21:58 UTC, khughes-bdai commented
@scastro-bdai i am nervous that renaming from `hand_pose()` could be a breaking change to external users -- although there already was a breaking change to this function with https://github.com/bdaiinstitute/spot_wrapper/pull/145 and there were no complaints 😅 
To your third point, we unfortunately can't use spatialmath `SE3` in this repo as it's not a dependency. I think a bosdyn `SE3Pose` could make sense as a default arg

2024-11-07 22:12 UTC, llee-bdai commented
@amessing-bdai pulling you into comments here because wer're all talking about the same thing. To answer your question as to if this is the function I recently fixed, yes, in terms of fixing it by removing ROS1 dependencies and actually using it. This isn't a breaking change for anything internal, but it would be breaking externally, technically.

@scastro-bdai @khughes-bdai 
1. I am not opposed to changing the name. The only reason it is named what it is now is because it has been this way since being written. If we were to rename it, I would agree to `set_arm_pose`
2. and 3. I would rather not make this an argument for now until we have a reason to make it an argument. We already have so many args into this function, I would hesitate to add more until we need it.

2024-11-08 14:03 UTC, amessing-bdai commented
Hmm, since we recently changed the signature already it's probably ok to further change it, but lets make sure this is the last change to the signature and not make this common practice.

2024-11-08 15:58 UTC, jbarry-bdai requested changes
IIRC the offset that it defaults to is the offset from the wrist to the center of the gripper, which is usually the "tool frame" people want.

I think this is probably not a desirable change especially this deep in the code in a repo that lots of people use...

2024-11-08 16:03 UTC, scastro-bdai commented
> IIRC the offset that it defaults to is the offset from the wrist to the center of the gripper, which is usually the "tool frame" people want.
> 
> I think this is probably not a desirable change especially this deep in the code in a repo that lots of people use...

I guess as a compromise, should we include the optional offset argument, and default it to the "sanctioned" tool frame?

2024-11-08 16:19 UTC, khughes-bdai commented
If you want to be explicitly commanding the wr1 link, it might make sense to make a new function called something like `wrist_pose`. This would eliminate any confusion with the pre-existing `hand_pose` function and make it clear that it's commanding a different link of the robot. thoughts?

2024-11-08 19:26 UTC, llee-bdai commented
I'm cool with @khughes-bdai suggestion of adding a whole new wrist pose function. But also, if we add another function, I wouldn't mind just adding in all the extra params required to specify wrist to some offset pose

2024-11-08 20:45 UTC, llee-bdai commented
On second thought, because this change ends up affecting a lot more than I expected, I am going to close this. Thanks for all the comments

2024-11-09 02:41 UTC, closed without merging